name: SafariNet
main: xyz.acrylicstyle.safarinet.SafariNetPlugin
version: "1.0.0-SNAPSHOT"
api-version: 1.20
commands:
  safarinet:
    description: Main command for SafariNet
    usage: /safarinet
    permission: safarinet.command
